[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pns_anchor = "EB6pbr3ZRnZv1bhgffQuuER5armxMRNauNWRabzuiaNj"

[programs.devnet]
pns_anchor = "EB6pbr3ZRnZv1bhgffQuuER5armxMRNauNWRabzuiaNj"

[idl]
path = "idl/"

[registry]
url = "https://github.com/coral-xyz/anchor"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pns_anchor_simple.ts"
