[toolchain]
anchor_version = "0.29.0"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
pns_anchor = "YOUR_PROGRAM_ID_HERE"

[programs.mainnet]
pns_anchor = "YOUR_PROGRAM_ID_HERE"

[registry]
url = "https://github.com/coral-xyz/anchor"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
